// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4u3PLPtqfSy1QEO9iUDC1i8FDJ4qYAds',
    appId: '1:541331614687:web:1a099720cd14b0e7deb26a',
    messagingSenderId: '541331614687',
    projectId: 'notificationalert-3088d',
    authDomain: 'notificationalert-3088d.firebaseapp.com',
    storageBucket: 'notificationalert-3088d.firebasestorage.app',
    measurementId: 'G-E5DFK5T86L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgK1VosnSGazyabt6DFQ_F52L_LMkhtz8',
    appId: '1:541331614687:android:d5e9df63f9016791deb26a',
    messagingSenderId: '541331614687',
    projectId: 'notificationalert-3088d',
    storageBucket: 'notificationalert-3088d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgFm0gbW6yE1IgOTs8GwZnFrMhqFI9z4',
    appId: '1:541331614687:ios:27b827d79d52b64ddeb26a',
    messagingSenderId: '541331614687',
    projectId: 'notificationalert-3088d',
    storageBucket: 'notificationalert-3088d.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhgFm0gbW6yE1IgOTs8GwZnFrMhqFI9z4',
    appId: '1:541331614687:ios:27b827d79d52b64ddeb26a',
    messagingSenderId: '541331614687',
    projectId: 'notificationalert-3088d',
    storageBucket: 'notificationalert-3088d.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4u3PLPtqfSy1QEO9iUDC1i8FDJ4qYAds',
    appId: '1:541331614687:web:0a11c3139e4ed943deb26a',
    messagingSenderId: '541331614687',
    projectId: 'notificationalert-3088d',
    authDomain: 'notificationalert-3088d.firebaseapp.com',
    storageBucket: 'notificationalert-3088d.firebasestorage.app',
    measurementId: 'G-M3R4S9NBGR',
  );
}
